audio:
  chunk_size: 261120
  dim_f: 4096
  dim_t: 256
  hop_length: 1024
  min_mean_abs: 0.001
  n_fft: 8192
  num_channels: 2
  sample_rate: 44100
augmentations:
  all:
    channel_shuffle: 0.5
    mp3_compression_backend: lameenc
    mp3_compression_max_bitrate: 320
    mp3_compression_min_bitrate: 32
    pedalboard_chorus: 0.001
    pedalboard_chorus_centre_delay_ms_max: 10
    pedalboard_chorus_centre_delay_ms_min: 3
    pedalboard_chorus_depth_max: 0.95
    pedalboard_chorus_depth_min: 0.25
    pedalboard_chorus_feedback_max: 0.01
    pedalboard_chorus_feedback_min: 0.0
    pedalboard_chorus_mix_max: 0.9
    pedalboard_chorus_mix_min: 0.1
    pedalboard_chorus_rate_hz_max: 7.0
    pedalboard_chorus_rate_hz_min: 1.0
    pedalboard_phazer: 0.001
    pedalboard_phazer_centre_frequency_hz_max: 12000
    pedalboard_phazer_centre_frequency_hz_min: 200
    pedalboard_phazer_depth_max: 0.95
    pedalboard_phazer_depth_min: 0.25
    pedalboard_phazer_feedback_max: 0.5
    pedalboard_phazer_feedback_min: 0.0
    pedalboard_phazer_mix_max: 0.9
    pedalboard_phazer_mix_min: 0.1
    pedalboard_phazer_rate_hz_max: 10.0
    pedalboard_phazer_rate_hz_min: 1.0
    pedalboard_pitch_shift: 0.01
    pedalboard_pitch_shift_semitones_max: 7
    pedalboard_pitch_shift_semitones_min: -7
    pedalboard_resample: 0.001
    pedalboard_resample_target_sample_rate_max: 44100
    pedalboard_resample_target_sample_rate_min: 4000
    random_inverse: 0.05
    random_polarity: 0.5
  dry:
    gaussian_noise: 0.005
    gaussian_noise_max_amplitude: 0.01
    gaussian_noise_min_amplitude: 0.001
    pedalboard_bitcrash: 0.005
    pedalboard_bitcrash_bit_depth_max: 16
    pedalboard_bitcrash_bit_depth_min: 4
    pedalboard_distortion: 0.001
    pedalboard_distortion_drive_db_max: 25.0
    pedalboard_distortion_drive_db_min: 1.0
    seven_band_parametric_eq: 0.24
    seven_band_parametric_eq_max_gain_db: 9
    seven_band_parametric_eq_min_gain_db: -9
    tanh_distortion: 0.05
    tanh_distortion_max: 0.7
    tanh_distortion_min: 0.1
    time_stretch: 0.01
    time_stretch_max_rate: 1.25
    time_stretch_min_rate: 0.8
  enable: false
  loudness: true
  loudness_max: 1.5
  loudness_min: 0.5
  mixup: true
  mixup_loudness_max: 1.5
  mixup_loudness_min: 0.5
  mixup_probs: !!python/tuple
  - 0.2
  - 0.02
  other:
    seven_band_parametric_eq: 0.24
    seven_band_parametric_eq_max_gain_db: 9
    seven_band_parametric_eq_min_gain_db: -9
inference:
  batch_size: 1
  dim_t: 256
  num_overlap: 4
model:
  act: gelu
  bottleneck_factor: 4
  growth: 128
  norm: InstanceNorm
  num_blocks_per_scale: 2
  num_channels: 128
  num_scales: 5
  num_subbands: 4
  scale:
  - 2
  - 2
training:
  batch_size: 2
  coarse_loss_clip: true
  ema_momentum: 0.999
  grad_clip: 0
  gradient_accumulation_steps: 1
  instruments:
  - dry
  - other
  lr: 1.0e-06
  num_epochs: 40
  num_steps: 1000
  optimizer: adamw
  other_fix: false
  patience: 4
  q: 0.95
  read_metadata_procs: 8
  reduce_factor: 0.93
  target_instrument: null
  use_amp: true
